name: animated_bottom_navigation_bar_nullsafe
description: Nullsafe version of https://github.com/LanarsInc/animated-bottom-navigation-bar-flutter
version: 0.0.2
homepage: https://github.com/TrishaDes/animated_bottom_navigation_bar-nullsafe/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
